# custom variables
title:              HexChat
url:                http://hexchat.github.io
version:            2.9.6.1

# permalinks
permalink:          /news/:title.html

# server
source:             ./source/
destination:        ./_site/
