# custom variables
title:              HexChat
url:                http://hexchat.github.io
dl_url:             http://dl.hexchat.net
version:            2.10.0

# permalinks
permalink:          /news/:title.html

exclude:            ["README.md"]

markdown:           kramdown
gems:
    - jekyll-sitemap
